import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 12 bytes is standard for GCM
const AUTH_TAG_LENGTH = 16; // 16 bytes auth tag

/**
 * Encrypts a string using AES-256-GCM.
 * Returns a hex-encoded string containing: iv + authTag + encryptedData
 */
export function encryptText(text: string): string {
  if (!text) return '';
  const keyHex = process.env.PIN_ENCRYPTION_KEY;
  if (!keyHex) {
    throw new Error('PIN_ENCRYPTION_KEY environment variable is missing.');
  }

  const key = Buffer.from(keyHex, 'hex');
  if (key.length !== 32) {
    throw new Error('PIN_ENCRYPTION_KEY must be a 64-character hex string (32 bytes).');
  }

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');

  const authTag = cipher.getAuthTag();

  // Format: iv(hex):authTag(hex):encrypted(hex)
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypts a hex-encoded string generated by encryptText.
 * Returns the decrypted string or null if decryption fails.
 */
export function decryptText(encryptedText: string | null | undefined): string | null {
  if (!encryptedText) return null;
  const keyHex = process.env.PIN_ENCRYPTION_KEY;
  if (!keyHex) {
    console.error('PIN_ENCRYPTION_KEY environment variable is missing.');
    return null;
  }

  try {
    const key = Buffer.from(keyHex, 'hex');
    const parts = encryptedText.split(':');
    if (parts.length !== 3) {
      return null;
    }

    const iv = Buffer.from(parts[0], 'hex');
    const authTag = Buffer.from(parts[1], 'hex');
    const encryptedData = parts[2];

    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);

    let decrypted = decipher.update(encryptedData, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
  } catch (error) {
    console.error('Decryption failed:', error);
    return null;
  }
}
